export const PLAYER_SUBMIT_REQUEST = "PLAYER_SUBMIT_REQUEST"
export const PLAYER_SUBMIT_SUCCESS = "PLAYER_SUBMIT_SUCCESS"
export const PLAYER_SUBMIT_FAIL = "PLAYER_SUBMIT_FAIL"

export const SCORE_UPDATE_REQUEST = "SCORE_UPDATE_REQUEST"
export const SCORE_UPDATE_SUCCESS = "SCORE_UPDATE_SUCCESS"
export const SCORE_UPDATE_FAIL = "SCORE_UPDATE_FAIL"
